apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: todo-service
  name: todo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: todo-service
    spec:
      containers:
      - image: ${ECR_REPOSITORY}:${IMAGE_TAG}
        imagePullPolicy: "Always"
        name: todo-service
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: todo-config
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: todo-service
spec:
  type: ClusterIP
  ports:
  - port: 3000
    protocol: TCP
  selector:
    app: todo-service
