name: Deploy to Middleware on Dev EKS Cluster
on:
  push:
    branches:
      - main  
env:
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_DEV }}
  EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME_DEV }}
  AWS_REGION: ${{ secrets.AWS_REGION_NAME }}
jobs:
  build:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
    - name: Set short git commit SHA
      id: commit
      uses: prompt/actions-commit-hash@v2
    - name: Check out code
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
        aws-region: ${{env.AWS_REGION}}
    - name: Setup Node Env
      uses: actions/setup-node@v3
      with:
        node-version: 21.1.0
    - name: Copy .env file
      env:
       ENV_FILE_CONTENT: ${{ secrets.DEV_ENV }}
      run: printf "%s" "$ENV_FILE_CONTENT" > manifest/configmap.yaml
    - name: Show PWD and list content
      run: |
           echo "Current Working Directory: pwd"
           pwd
           ls -ltra
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ secrets.ECR_REPOSITORY }}
        IMAGE_TAG: ${{ secrets.IMAGE_TAG_DEV }}
      run: |
        docker build -t ${{ secrets.ECR_REPOSITORY }}:${{ secrets.IMAGE_TAG_DEV }} .
        docker push ${{ secrets.ECR_REPOSITORY }}:${{ secrets.IMAGE_TAG_DEV }}
    - name: Update kube config
      run: aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME_DEV }} --region ${{ secrets.AWS_REGION_NAME }}
    - name: Deploy to EKS
      env:
        ECR_REGISTRY: ${{ secrets.ECR_REPOSITORY }}
        IMAGE_TAG: ${{ env.IMAGE_TAG_DEV }}
        
      run: |
        export ECR_REPOSITORY=${{ secrets.ECR_REPOSITORY }}
        export IMAGE_TAG=${{ secrets.IMAGE_TAG_DEV }}
        export ECR_IMAGE=${{ secrets.ECR_IMAGE_DEV }}
        envsubst < manifest/todo-service.yaml > manifest/todo-service-updated.yaml
        cat manifest/todo-service-updated.yaml
        rm -rf manifest/todo-service.yaml
        kubectl delete deployment todo-service
        kubectl delete service todo-service
        kubectl delete cm todo-config
        kubectl apply -f manifest/todo-updated.yaml
        kubectl apply -f manifest/configmap.yaml
        sleep 10
        kubectl get pods
        kubectl get services
        kubectl get deployment 
