name: Deploy to Tekdi-QA-Server
on:
  push:
    branches:
      - main
jobs:
   todo_service_deploy_on_Tekdi_QA_Server:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - 
      name: Deploy Stack
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.HOST_NAME_TEKDI_QA }}
          username: ${{ secrets.USERNAME_TEKDI_QA }}
          key: ${{ secrets.EC2_SSH_KEY_TEKDI_QA }}
          port: ${{ secrets.PORT_TEKDI_QA }}
          script: |    
               cd ${{ secrets.TARGET_DIR_TEKDI_QA }}
               if [ -f .env ]; then
               rm .env
               fi
               echo '${{ secrets.QA_ENV }}' > .env
               ls -ltra
               ./deploy.sh
